site_name: OpenWrt.io
pages:
- 首页: index.md
- 文档:
    - '新手指南': 'docs/beginners-guide.md'
    - '支持的硬件': 'docs/supported-devices.md'
    - '开发者指南': 'docs/developer-guide.md'
    - '极路由': 'docs/gee.md'
    - '优酷路由宝': 'docs/youku.md'
- 关于我们: about.md
theme: readthedocs
repo_url: https://github.com/abcabc1/idoc.git
repo_name: Coding
site_favicon: favicon.ico
copyright: 
